/**
 * Data generation pipeline.
 *
 * Fetches a pinned snapshot of the REST Countries v3.1 dataset, validates it,
 * vendors the raw JSON into `data/`, and generates the typed data module and
 * string-literal union types into `src/generated/`.
 *
 * Run with: `npm run generate`
 *
 * The package ships the generated output; consumers never fetch anything.
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

// Pinned to a specific commit for reproducible builds.
const SOURCE_COMMIT = 'ff97f12bb61f8cbc389228d53445f64102cc305f';
const SOURCE_URL = `https://gitlab.com/restcountries/restcountries/-/raw/${SOURCE_COMMIT}/src/main/resources/countriesV3.1.json`;
const RAW_PATH = join(ROOT, 'data', 'countries.raw.json');

const REQUIRED_KEYS = [
  'name', 'tld', 'cca2', 'ccn3', 'cca3', 'cioc', 'fifa', 'independent',
  'status', 'unMember', 'currencies', 'idd', 'capital', 'capitalInfo',
  'altSpellings', 'region', 'subregion', 'continents', 'languages',
  'translations', 'latlng', 'landlocked', 'borders', 'area', 'flag',
  'demonyms', 'flags', 'coatOfArms', 'population', 'maps', 'gini', 'car',
  'postalCode', 'startOfWeek', 'timezones',
] as const;

interface RawCountry {
  [key: string]: unknown;
  cca2: string;
  cca3: string;
  ccn3: string;
  cioc: string;
  region: string;
  subregion: string;
  continents: string[];
  currencies: Record<string, unknown>;
  languages: Record<string, string>;
}

async function loadRaw(): Promise<string> {
  const offline = process.argv.includes('--offline');
  if (offline && existsSync(RAW_PATH)) {
    console.log('Using vendored snapshot (--offline):', RAW_PATH);
    return readFileSync(RAW_PATH, 'utf8');
  }
  console.log('Fetching', SOURCE_URL);
  const res = await fetch(SOURCE_URL);
  if (!res.ok) {
    throw new Error(`Fetch failed: ${res.status} ${res.statusText}`);
  }
  return res.text();
}

/**
 * Light normalization of genuinely-empty values so the typed shape stays
 * clean. Currently: drop `capitalInfo.latlng` when it is an empty array
 * (5 territories with no capital coordinates), making the field optional.
 */
function normalize(data: RawCountry[]): RawCountry[] {
  for (const c of data) {
    const ci = c.capitalInfo as { latlng?: unknown } | undefined;
    if (ci && Array.isArray(ci.latlng) && ci.latlng.length < 2) {
      delete ci.latlng;
    }
  }
  return data;
}

function validate(data: unknown): asserts data is RawCountry[] {
  if (!Array.isArray(data)) throw new Error('Dataset is not an array');
  if (data.length < 240 || data.length > 260) {
    throw new Error(`Unexpected country count: ${data.length} (expected ~250)`);
  }
  for (const c of data) {
    for (const key of REQUIRED_KEYS) {
      if (!(key in (c as object))) {
        throw new Error(`Country ${(c as RawCountry).cca3} missing key: ${key}`);
      }
    }
  }
}

function uniqueSorted(values: Iterable<string>): string[] {
  return [...new Set([...values].filter(Boolean))].sort();
}

function unionType(name: string, values: string[]): string {
  if (values.length === 0) return `export type ${name} = string;\n`;
  const body = values.map((v) => `  | ${JSON.stringify(v)}`).join('\n');
  return `export type ${name} =\n${body};\n`;
}

function constArray(name: string, type: string, values: string[]): string {
  const body = values.map((v) => `  ${JSON.stringify(v)},`).join('\n');
  return `export const ${name}: readonly ${type}[] = [\n${body}\n] as const;\n`;
}

function generateCodes(data: RawCountry[]): string {
  const cca2 = uniqueSorted(data.map((c) => c.cca2));
  const cca3 = uniqueSorted(data.map((c) => c.cca3));
  const ccn3 = uniqueSorted(data.map((c) => c.ccn3));
  const cioc = uniqueSorted(data.map((c) => c.cioc));
  const currency = uniqueSorted(data.flatMap((c) => Object.keys(c.currencies)));
  const language = uniqueSorted(data.flatMap((c) => Object.keys(c.languages)));
  const region = uniqueSorted(data.map((c) => c.region));
  const subregion = uniqueSorted(data.map((c) => c.subregion));
  const continent = uniqueSorted(data.flatMap((c) => c.continents));

  return [
    '// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.',
    `// Source: REST Countries v3.1 @ ${SOURCE_COMMIT}`,
    `// Generated: ${new Date().toISOString()}`,
    '',
    `export const provenance = {`,
    `  source: 'REST Countries v3.1',`,
    `  url: ${JSON.stringify(SOURCE_URL)},`,
    `  commit: ${JSON.stringify(SOURCE_COMMIT)},`,
    `  generatedAt: ${JSON.stringify(new Date().toISOString())},`,
    `  count: ${data.length},`,
    `} as const;`,
    '',
    unionType('Cca2', cca2),
    unionType('Cca3', cca3),
    unionType('Ccn3', ccn3),
    unionType('Cioc', cioc),
    unionType('CurrencyCode', currency),
    unionType('LanguageCode', language),
    unionType('Region', region),
    unionType('Subregion', subregion),
    unionType('Continent', continent),
    constArray('cca2Codes', 'Cca2', cca2),
    constArray('cca3Codes', 'Cca3', cca3),
    constArray('ccn3Codes', 'Ccn3', ccn3),
    constArray('ciocCodes', 'Cioc', cioc),
    constArray('currencyCodes', 'CurrencyCode', currency),
    constArray('languageCodes', 'LanguageCode', language),
    constArray('regions', 'Region', region),
    constArray('subregions', 'Subregion', subregion),
    constArray('continents', 'Continent', continent),
  ].join('\n');
}

function generateCountries(data: RawCountry[]): string {
  return [
    '// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.',
    `// Source: REST Countries v3.1 @ ${SOURCE_COMMIT}`,
    '',
    "import type { Country } from '../types';",
    '',
    `export const countries: Country[] = ${JSON.stringify(data, null, 2)};`,
    '',
  ].join('\n');
}

function generateIndex(): string {
  return [
    '// AUTO-GENERATED by scripts/generate.ts — do not edit by hand.',
    "export { countries } from './countries';",
    "export * from './codes';",
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const rawText = await loadRaw();
  const parsed = JSON.parse(rawText) as unknown;
  validate(parsed);

  mkdirSync(join(ROOT, 'data'), { recursive: true });
  mkdirSync(join(ROOT, 'src', 'generated'), { recursive: true });

  // Vendor the raw snapshot verbatim (provenance / audit) before normalizing.
  writeFileSync(RAW_PATH, JSON.stringify(parsed, null, 0) + '\n');

  const data = normalize(parsed);

  writeFileSync(join(ROOT, 'src', 'generated', 'codes.ts'), generateCodes(data));
  writeFileSync(join(ROOT, 'src', 'generated', 'countries.ts'), generateCountries(data));
  writeFileSync(join(ROOT, 'src', 'generated', 'index.ts'), generateIndex());

  console.log(`Generated ${data.length} countries.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
